List days = [
  {"label": "Sun", "day": "28"},
  {"label": "Mon", "day": "29"},
  {"label": "Tue", "day": "30"},
  {"label": "Wed", "day": "31"},
  {"label": "Thu", "day": "1"},
  {"label": "Fri", "day": "2"},
  {"label": "Sat", "day": "3"},
];

List months = [
  {"label": "2022", "month": "Jan", "id": 1},
  {"label": "2022", "month": "Feb", "id": 2},
  {"label": "2022", "month": "Mar", "id": 3},
  {"label": "2022", "month": "Apr", "id": 4},
  {"label": "2022", "month": "May", "id": 5},
  {"label": "2022", "month": "Jun", "id": 6},
  {"label": "2022", "month": "Jul", "id": 7},
  {"label": "2022", "month": "Aug", "id": 8},
  {"label": "2022", "month": "Sep", "id": 9},
  {"label": "2022", "month": "Oct", "id": 10},
  {"label": "2022", "month": "Nov", "id": 11},
  {"label": "2022", "month": "Dec", "id": 12},
];

List dailyTransaction = [
  {
    "name": "Bank Deposit",
    "date": "Jun",
    "price": "100000",
    "remarks": "Today's collection depoist",
    "type": "OUT",
    // "vehicleId": 1,
  },
  {
    "name": "Maintainence & Repair",
    "date": "Jun",
    "price": "20000",
    "remarks": "Tyre and breaks of Gaadi 1",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "May",
    "price": "30000",
    "remarks": "Gaadi 1 service income",
    "type": "IN",
  },
  {
    "name": "Salary",
    "date": "May",
    "price": "30000",
    "remarks": "Salary paid to both drivers",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Jan",
    "price": "24000",
    "remarks": "Gaadi 2 service income",
    "type": "IN",
  },
  {
    "name": "Personal Expense",
    "date": "Feb",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Salary",
    "date": "Sun 9 AM",
    "price": "30000",
    "remarks": "Salary paid to both drivers",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Fri 8 PM",
    "price": "24000",
    "remarks": "Gaadi 2 service income",
    "type": "IN",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Mar",
    "price": "10000",
    "remarks": "Gaadi 2 service income",
    "type": "IN",
  },
];
