List days = [
  {"label": "Sun", "day": "28"},
  {"label": "Mon", "day": "29"},
  {"label": "Tue", "day": "30"},
  {"label": "Wed", "day": "31"},
  {"label": "Thu", "day": "1"},
  {"label": "Fri", "day": "2"},
  {"label": "Sat", "day": "3"},
];

List months = [
  {"label": "2022", "month": "Jan"},
  {"label": "2022", "month": "Feb"},
  {"label": "2022", "month": "Mar"},
  {"label": "2022", "month": "Apr"},
  {"label": "2022", "month": "May"},
  {"label": "2022", "month": "Jun"},
  {"label": "2022", "month": "Jul"},
  {"label": "2022", "month": "Aug"},
  {"label": "2022", "month": "Sep"},
  {"label": "2022", "month": "Oct"},
  {"label": "2022", "month": "Nov"},
  {"label": "2022", "month": "Dec"},
];

List dailyTransaction = [
  {
    "name": "Bank Deposit",
    "date": "Mon 11 AM",
    "price": "100000",
    "remarks": "Today's collection depoist",
    "type": "OUT",
    // "vehicleId": 1,
  },
  {
    "name": "Maintainence & Repair",
    "date": "Fri 8 AM",
    "price": "20000",
    "remarks": "Tyre and breaks of Gaadi 1",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Fri 8 PM",
    "price": "30000",
    "remarks": "Gaadi 1 service income",
    "type": "IN",
  },
  {
    "name": "Salary",
    "date": "Sun 9 AM",
    "price": "30000",
    "remarks": "Salary paid to both drivers",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Fri 8 PM",
    "price": "24000",
    "remarks": "Gaadi 2 service income",
    "type": "IN",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Salary",
    "date": "Sun 9 AM",
    "price": "30000",
    "remarks": "Salary paid to both drivers",
    "type": "OUT",
  },
  {
    "name": "Income",
    "date": "Fri 8 PM",
    "price": "24000",
    "remarks": "Gaadi 2 service income",
    "type": "IN",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
  {
    "name": "Personal Expense",
    "date": "Thu 4 PM",
    "price": "5000",
    "remarks": "Allowance taken",
    "type": "OUT",
  },
];
